test error

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,7 +4,7 @@
 
 name: 💡🏠
 
-on: [pull_request]
+on: [push]
 
 jobs:
   ci:
@@ -54,32 +54,32 @@ jobs:
     - run: yarn --frozen-lockfile
     - run: yarn build-all
     - run: yarn diff:sample-json
-    - run: yarn type-check
-    - run: yarn lint
+    # - run: yarn type-check
+    # - run: yarn lint
     - run: yarn test-proto # Run before unit-core because the roundtrip json is needed for proto tests.
 
     # Run tests that require headfull Chrome.
     - run: sudo apt-get install xvfb
     - run: xvfb-run --auto-servernum yarn unit
-    - run: xvfb-run --auto-servernum yarn test-clients
-    - run: xvfb-run --auto-servernum yarn smoke -j=1 --retries=2
-    - run: xvfb-run --auto-servernum yarn test-bundle
-    - run: xvfb-run --auto-servernum yarn test-docs
+    # - run: xvfb-run --auto-servernum yarn test-clients
+    # - run: xvfb-run --auto-servernum yarn smoke -j=1 --retries=2
+    # - run: xvfb-run --auto-servernum yarn test-bundle
+    # - run: xvfb-run --auto-servernum yarn test-docs
 
-    - run: yarn test-lantern
-    - run: yarn test-legacy-javascript
-    - run: yarn i18n:checks
-    - run: yarn dogfood-lhci
+    # - run: yarn test-lantern
+    # - run: yarn test-legacy-javascript
+    # - run: yarn i18n:checks
+    # - run: yarn dogfood-lhci
 
     # buildtracker runs `git merge-base HEAD origin/master` which needs more history than depth=1. https://github.com/paularmstrong/build-tracker/issues/106
-    - name: Deepen git fetch (for buildtracker)
-      run: git fetch --deepen=100
-    - name: Store in buildtracker
+    # - name: Deepen git fetch (for buildtracker)
+      # run: git fetch --deepen=100
+    # - name: Store in buildtracker
       # TODO(paulirish): Don't allow this to fail the build. https://github.com/paularmstrong/build-tracker/issues/200
-      run: yarn bt-cli upload-build || true
-      env:
+      # run: yarn bt-cli upload-build || true
+      # env:
         # https://buildtracker.dev/docs/guides/github-actions#configuration
-        BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}
+        # BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}
 
     # Fail if any changes were written to source files (ex, from: build/build-cdt-lib.js).
-    - run: git diff --exit-code
+    # - run: git diff --exit-code
