commentout

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,99 +4,99 @@
 
 name: 💡🏠
 
-on: [pull_request]
+on: [pull_request, push]
 
 jobs:
-  # `basics` includes all non-smoke CI, except for unit and proto
-  basics:
-    runs-on: ubuntu-latest
+  # # `basics` includes all non-smoke CI, except for unit and proto
+  # basics:
+  #   runs-on: ubuntu-latest
 
-    # A few steps are duplicated across all jobs. Can be done better when this feature lands:
-    #   https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851
-    #   https://github.com/actions/runner/issues/438
-    steps:
-    - name: git clone
-      uses: actions/checkout@v2
+  #   # A few steps are duplicated across all jobs. Can be done better when this feature lands:
+  #   #   https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851
+  #   #   https://github.com/actions/runner/issues/438
+  #   steps:
+  #   - name: git clone
+  #     uses: actions/checkout@v2
 
-    - name: Use Node.js 10.x
-      uses: actions/setup-node@v1
-      with:
-        node-version: 10.x
+  #   - name: Use Node.js 10.x
+  #     uses: actions/setup-node@v1
+  #     with:
+  #       node-version: 10.x
 
-    - run: yarn --frozen-lockfile
-    - run: yarn build-all
+  #   - run: yarn --frozen-lockfile
+  #   - run: yarn build-all
 
-    # Run tests that require headfull Chrome.
-    - run: sudo apt-get install xvfb
-    - name: yarn test-clients
-      run: xvfb-run --auto-servernum yarn test-clients
-    - name: yarn test-bundle
-      run: xvfb-run --auto-servernum yarn test-bundle
-    - name: yarn test-docs
-      run: xvfb-run --auto-servernum yarn test-docs
+  #   # Run tests that require headfull Chrome.
+  #   - run: sudo apt-get install xvfb
+  #   - name: yarn test-clients
+  #     run: xvfb-run --auto-servernum yarn test-clients
+  #   - name: yarn test-bundle
+  #     run: xvfb-run --auto-servernum yarn test-bundle
+  #   - name: yarn test-docs
+  #     run: xvfb-run --auto-servernum yarn test-docs
 
-    - run: yarn diff:sample-json
-    - run: yarn type-check
-    - run: yarn lint
-    - run: yarn test-lantern
-    - run: yarn test-legacy-javascript
-    - run: yarn i18n:checks
-    - run: yarn dogfood-lhci
+  #   - run: yarn diff:sample-json
+  #   - run: yarn type-check
+  #   - run: yarn lint
+  #   - run: yarn test-lantern
+  #   - run: yarn test-legacy-javascript
+  #   - run: yarn i18n:checks
+  #   - run: yarn dogfood-lhci
 
-    # buildtracker runs `git merge-base HEAD origin/master` which needs more history than depth=1. https://github.com/paularmstrong/build-tracker/issues/106
-    - name: Deepen git fetch (for buildtracker)
-      run: git fetch --deepen=100
-    - name: Store in buildtracker
-      # TODO(paulirish): Don't allow this to fail the build. https://github.com/paularmstrong/build-tracker/issues/200
-      run: yarn bt-cli upload-build || true
-      env:
-        # https://buildtracker.dev/docs/guides/github-actions#configuration
-        BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}
+  #   # buildtracker runs `git merge-base HEAD origin/master` which needs more history than depth=1. https://github.com/paularmstrong/build-tracker/issues/106
+  #   - name: Deepen git fetch (for buildtracker)
+  #     run: git fetch --deepen=100
+  #   - name: Store in buildtracker
+  #     # TODO(paulirish): Don't allow this to fail the build. https://github.com/paularmstrong/build-tracker/issues/200
+  #     run: yarn bt-cli upload-build || true
+  #     env:
+  #       # https://buildtracker.dev/docs/guides/github-actions#configuration
+  #       BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}
 
-    - name: Upload dist
-      uses: actions/upload-artifact@v1
-      with:
-        name: dist
-        path: dist/
+  #   - name: Upload dist
+  #     uses: actions/upload-artifact@v1
+  #     with:
+  #       name: dist
+  #       path: dist/
 
-    # Fail if any changes were written to source files (ex, from: build/build-cdt-lib.js).
-    - run: git diff --exit-code
+  #   # Fail if any changes were written to source files (ex, from: build/build-cdt-lib.js).
+  #   - run: git diff --exit-code
 
-  # `unit` includes just unit and proto tests.
-  unit:
-    runs-on: ubuntu-latest
+  # # `unit` includes just unit and proto tests.
+  # unit:
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - name: git clone
-      uses: actions/checkout@v2
+  #   steps:
+  #   - name: git clone
+  #     uses: actions/checkout@v2
 
-    - name: Use Node.js 10.x
-      uses: actions/setup-node@v1
-      with:
-        node-version: 10.x
+  #   - name: Use Node.js 10.x
+  #     uses: actions/setup-node@v1
+  #     with:
+  #       node-version: 10.x
 
-    - name: Set up protoc
-      uses: arduino/setup-protoc@7ad700d
-      with:
-        version: '3.7.1'
-        repo-token: ${{ secrets.GITHUB_TOKEN }}
+  #   - name: Set up protoc
+  #     uses: arduino/setup-protoc@7ad700d
+  #     with:
+  #       version: '3.7.1'
+  #       repo-token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Set up Python
-      uses: actions/setup-python@v1
-      with:
-        python-version: 2.7
-    - name: Install Python dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install protobuf==3.7.1
+  #   - name: Set up Python
+  #     uses: actions/setup-python@v1
+  #     with:
+  #       python-version: 2.7
+  #   - name: Install Python dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install protobuf==3.7.1
 
-    - run: yarn --frozen-lockfile
+  #   - run: yarn --frozen-lockfile
 
-    - run: yarn test-proto # Run before unit-core because the roundtrip json is needed for proto tests.
+  #   - run: yarn test-proto # Run before unit-core because the roundtrip json is needed for proto tests.
 
-    - run: sudo apt-get install xvfb
-    - name: yarn unit
-      run: xvfb-run --auto-servernum yarn unit
+  #   - run: sudo apt-get install xvfb
+  #   - name: yarn unit
+  #     run: xvfb-run --auto-servernum yarn unit
 
   # `smoke` runs as a matrix across 4 jobs:
   #  * The smoketest groups are split across two runners, to parallelize.
@@ -137,8 +137,8 @@ jobs:
     - run: echo "chromepath is $CHROME_PATH . invert is ${{ matrix.smoke-test-invert }}"
     - run: yarn --frozen-lockfile
 
-    - run: sudo apt-get install xvfb
+    # - run: sudo apt-get install xvfb
 
 
-    - name: Run smoke tests
-      run: xvfb-run --auto-servernum yarn smoke --debug -j=1 --retries=2 --invert-match ${{ matrix.smoke-test-invert }} $SMOKE_GROUP_1
+    # - name: Run smoke tests
+    #   run: xvfb-run --auto-servernum yarn smoke --debug -j=1 --retries=2 --invert-match ${{ matrix.smoke-test-invert }} $SMOKE_GROUP_1
